export default {
    products: [
        {
            "_id": "593e9297e17df20c4a237d42",
            "name": "Hidden Gem In the Center Of Tirana",
            "index": 0,
            "price": "58,000",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "image": "https://cdn.vox-cdn.com/thumbor/B2Ca5KWYL9ZKYEVJBBZ5Hv5NuHE=/1400x788/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/11545789/House_Calls_Soldi_Caillier_Tacoma__WA_living_room_Rafael_Soldi.jpg",
            "city": "Tirana",
            "description": 'This amazing and spacious apartment is the perfect choice for those wishing to visit the city of Tirana and its surroundings, and see it through of a true local! Gallery Apart Hotel Tirana, is o modern and minimalist apartment situated at the heart of Tirana, just walking distance from the best restaurants coffees and night life in the city. It is a fully equipped apartament with everything You need to feel like home away from home.',
            "address": "Rruga Mine Peza",
            "latitude": 41.330044,
            "longitude": 19.814541,
            "bedrooms": 2,
            "bathrooms": 2,
            "carSpaces": 2
        },
        {
            "_id": "593e9297ec4cca9c56bf61af",
            "name": "Deluxe Apartment Y",
            "index": 1,
            "price": 703725,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "image": "https://www.studentcastle.co.uk/media/2123/2234_0019.jpg?anchor=middlecenter&mode=crop&quality=75&format=jpg&scale=both&width=1200&height=750",
            "city": "Tirana",
            "address": "Rruga e Durrësit",
            "latitude": 41.332572,
            "longitude": 19.805032,
            "bedrooms": 2,
            "bathrooms": 1,
            "carSpaces": 0,
            "countInStock": 6,
        },
        {
            "_id": "593e929773c71925e5d7c11c",
            "index": 2,
            "price": 837111,
            "name": "Coolest Apartment in town",
            "image": "https://i.pinimg.com/originals/bd/54/54/bd5454383c17d7c748381f511230fe05.jpg",
            "city": "Tirana",
            "address": "Rruga Hysni Gërbolli",
            "latitude": 41.334484,
            "longitude": 19.804664,
            "bedrooms": 3,
            "bathrooms": 2,
            "carSpaces": 0
        },
        {
            "_id": "593e92973d4d15eedb129aee",
            "index": 3,
            "price": 648223,
            "image": "https://studentstay.co.uk/media/properties/images/VibeStudentLiving-Studio-May17.jpg",
            "city": "Tirana",
            "address": "Don Bosco",
            "latitude": 41.334685,
            "longitude": 19.807052,
            "bedrooms": 3,
            "bathrooms": 2,
            "carSpaces": 0
        },
        {
            "_id": "593e929728b7f8543b7907e1",
            "index": 4,
            "price": 771826,
            "image": "https://lh3.googleusercontent.com/proxy/VE4K-hKshvrnPsUFsaM-_LDgIv8pkaEdPCnPhKQsyl7-WmIIrwucAeLujehEoyYgh5qBTaskZrNEQZsHNzl0ZVtX_fQyxF0D-RUlgvECsVQSvLnqmA_MUS5AdO9ghCSD3FjyLiUIyg",
            "city": "Tirana",
            "address": "Rruga Studenti",
            "latitude": 41.328387,
            "longitude": 19.800213,
            "bedrooms": 2,
            "bathrooms": 1,
            "carSpaces": 1
        },
        {
            "_id": "593e92975996a6263d146444",
            "index": 5,
            "price": 686238,
            "image": "https://student-cribs.com/assets/cbf1814569ba316686657265bf62102a.jpg",
            "city": "Tirana",
            "address": "Rruga Studenti",
            "latitude": 41.329240,
            "longitude": 19.800053,
            "bedrooms": 2,
            "bathrooms": 1,
            "carSpaces": 1
        },
        {
            "_id": "593e9297a13e246da5ba0884",
            "index": 6,
            "price": 595377,
            "image": "https://imagesplace.files.wordpress.com/2010/10/wpid-image-0271-the-perfect-student-s-crib-small-but-well-organized-abode-3.jpg",
            "city": "Tirana",
            "address": "Rruga Frosina Plaku",
            "latitude": 41.327699,
            "longitude": 19.802194,
            "bedrooms": 2,
            "bathrooms": 2,
            "carSpaces": 2
        },
        {
            "_id": "593e9297afa51a013fcd07d5",
            "index": 7,
            "price": 696189,
            "image": "https://www.opus-group.com/Media/ProjectImages/Iowa-State-University-Private-Student-Housing_5982_1000x667.jpg?v=637082032940000000",
            "city": "Tirana",
            "address": "Rruga Sandër Prosi",
            "latitude": 41.328497,
            "longitude": 19.803653,
            "bedrooms": 4,
            "bathrooms": 1,
            "carSpaces": 1
        },
        {
            "_id": "593e92972bd8fd05f2ab1a89",
            "index": 8,
            "price": 716114,
            "image": "https://s3-eu-west-1.amazonaws.com/studentcribs/cribs/big_1078-furness-road_bd315d32.jpg",
            "city": "Tirana",
            "address": "Rruga Frosina Plaku",
            "latitude": 41.327527,
            "longitude": 19.801693,
            "bedrooms": 3,
            "bathrooms": 1,
            "carSpaces": 0
        },
        {
            "_id": "593e9297fe2e6d32c859ecf4",
            "index": 9,
            "price": 739852,
            "image": "https://i.redd.it/f25n8kcszom01.jpg",
            "city": "Tirana",
            "address": "Rruga Kongresi i Lushnjes",
            "latitude": 41.326528,
            "longitude": 19.801993,
            "bedrooms": 2,
            "bathrooms": 1,
            "carSpaces": 1
        },
        {
            "_id": "593e92970481ccf52f948e6d",
            "index": 10,
            "price": 625917,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property01.jpg",
            "city": "Tirana",
            "address": "Kryqëzimi 21 Dhjetori",
            "latitude": 41.325948,
            "longitude": 19.802969,
            "bedrooms": 4,
            "bathrooms": 1,
            "carSpaces": 2
        },
        {
            "_id": "593e9297e09417746b79e1c5",
            "index": 11,
            "price": 591236,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property02.jpg",
            "city": "Tirana",
            "address": "Rruga Besim Imami",
            "latitude": 41.324902,
            "longitude": 19.808798,
            "bedrooms": 2,
            "bathrooms": 1,
            "carSpaces": 0
        },
        {
            "_id": "593e92978e7160fa2b9992d9",
            "index": 12,
            "price": 995539,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property03.jpg",
            "city": "Tirana",
            "address": "Rruga Vangjush Furxhi",
            "latitude": 41.324217,
            "longitude": 19.810815,
            "bedrooms": 1,
            "bathrooms": 2,
            "carSpaces": 0
        },
        {
            "_id": "593e92973459fbdfa1f1c041",
            "index": 13,
            "price": 866924,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property04.jpg",
            "city": "Tirana",
            "address": "Rruga e Kavajës",
            "latitude": 41.328095,
            "longitude": 19.813007,
            "bedrooms": 1,
            "bathrooms": 1,
            "carSpaces": 2
        },
        {
            "_id": "593e92970306538830483e14",
            "index": 14,
            "price": 810745,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property05.jpg",
            "city": "Tirana",
            "address": "Rruga Myslym Shyri",
            "latitude": 41.325621,
            "longitude": 19.816247,
            "bedrooms": 2,
            "bathrooms": 2,
            "carSpaces": 2
        },
        {
            "_id": "593e92976042982766c97ca1",
            "index": 15,
            "price": 793134,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property01.jpg",
            "city": "Tirana",
            "address": "Rruga Njazi Demi",
            "latitude": 41.321296,
            "longitude": 19.807648,
            "bedrooms": 2,
            "bathrooms": 1,
            "carSpaces": 0
        },
        {
            "_id": "593e92971901e888a036a258",
            "index": 16,
            "price": 984589,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property02.jpg",
            "city": "Tirana",
            "address": "Rruga e Elbasanit",
            "latitude": 41.321553,
            "longitude": 19.825978,
            "bedrooms": 1,
            "bathrooms": 1,
            "carSpaces": 1
        },
        {
            "_id": "593e929780e6af9c11a10b90",
            "index": 17,
            "price": 836244,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property03.jpg",
            "city": "Tirana",
            "address": "Rruga e Elbasanit",
            "latitude": 41.322958,
            "longitude": 19.824669,
            "bedrooms": 1,
            "bathrooms": 2,
            "carSpaces": 0
        },
        {
            "_id": "593e9297441033e3f818ff6b",
            "index": 18,
            "price": 962426,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property04.jpg",
            "city": "Tirana",
            "address": "Rruga e Elbasanit",
            "latitude": 41.323740,
            "longitude": 19.825163,
            "bedrooms": 3,
            "bathrooms": 2,
            "carSpaces": 1
        },
        {
            "_id": "593e9297964d25b59d94e8aa",
            "index": 19,
            "price": 768916,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property05.jpg",
            "city": "Tirana",
            "address": "Rruga Pjeter Budi",
            "latitude": 41.320942,
            "longitude": 19.829826,
            "bedrooms": 3,
            "bathrooms": 2,
            "carSpaces": 0
        },
        {
            "_id": "593e929737636c879539416d",
            "index": 20,
            "price": 956974,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property01.jpg",
            "city": "Tirana",
            "address": "Rruga Arben Broci",
            "latitude": 41.320048,
            "longitude": 19.832433,
            "bedrooms": 1,
            "bathrooms": 1,
            "carSpaces": 1
        },
        {
            "_id": "593e9297b2516c3e5af4601f",
            "index": 21,
            "price": 875917,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property02.jpg",
            "city": "Tirana",
            "address": "Rruga Brigada e VIII",
            "latitude": 41.322016,
            "longitude": 19.815888,
            "bedrooms": 2,
            "bathrooms": 1,
            "carSpaces": 2
        },
        {
            "_id": "593e92972f6034590df04c45",
            "index": 22,
            "price": 913858,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property03.jpg",
            "city": "Tirana",
            "address": "Rruga Andon Zako Çajupi",
            "latitude": 41.319143,
            "longitude": 19.813013,
            "bedrooms": 3,
            "bathrooms": 1,
            "carSpaces": 2
        },
        {
            "_id": "593e9297aa0e233a421f1a58",
            "index": 23,
            "price": 622995,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property04.jpg",
            "city": "Tirana",
            "address": "Rruga Bardhok Biba",
            "latitude": 41.330735,
            "longitude": 19.819697,
            "bedrooms": 2,
            "bathrooms": 2,
            "carSpaces": 0
        },
        {
            "_id": "593e92977526a30b580dcfb2",
            "index": 24,
            "price": 593777,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property05.jpg",
            "city": "Tirana",
            "address": "Rruga Qemal Stafa",
            "latitude": 41.330611,
            "longitude": 19.822275,
            "bedrooms": 2,
            "bathrooms": 2,
            "carSpaces": 1
        },
        {
            "_id": "593e92975141c74b24375bd9",
            "index": 25,
            "price": 757686,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property01.jpg",
            "city": "Tirana",
            "address": "Rruga Qemal Stafa",
            "latitude": 41.331304,
            "longitude": 19.824796,
            "bedrooms": 3,
            "bathrooms": 1,
            "carSpaces": 1
        },
        {
            "_id": "593e9297b3ffeb95bb008453",
            "index": 26,
            "price": 976878,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property02.jpg",
            "city": "Tirana",
            "address": "Rruga Kostandin Kristoforidhi",
            "latitude": 41.329733,
            "longitude": 19.822200,
            "bedrooms": 3,
            "bathrooms": 1,
            "carSpaces": 0
        },
        {
            "_id": "593e9297e262c91acd91ab81",
            "index": 27,
            "price": 804859,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property03.jpg",
            "city": "Tirana",
            "address": "Rruga",
            "latitude": 41.334933,
            "longitude": 19.818481,
            "bedrooms": 1,
            "bathrooms": 2,
            "carSpaces": 0
        },
        {
            "_id": "593e9297df21e62e0465f91f",
            "index": 28,
            "price": 611018,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property04.jpg",
            "city": "Tirana",
            "address": "Rruga 4 Dëshmorët",
            "latitude": 41.335531,
            "longitude": 19.827488,
            "bedrooms": 2,
            "bathrooms": 1,
            "carSpaces": 2
        },
        {
            "_id": "593e929787f567dccda86910",
            "index": 29,
            "price": 707939,
            "image": "https://ihatetomatoes.net/demos/_rw/01-real-estate/tn_property05.jpg",
            "city": "Tirana",
            "address": "Rruga Spiro Moisiu",
            "latitude": 41.328812,
            "longitude": 19.829621,
            "bedrooms": 1,
            "bathrooms": 1,
            "carSpaces": 1
        }
    ]
}
